version: '3.8'

services:
  postgres:
    image: bitnami/postgresql
    container_name: gestao_vagas_postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=gestao_vagas